config/routes.rb
Rails.application.routes.draw do

  root 'welcome#homepage'
  
  get '/login', to: 'sessions#new'
  post 'sessions', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
  
  get "/plants/:id", to: "plants#show", as: "plants"
  # get "/users/:id", to: "users#show", as: "users"

  



  resources :user_plants
  resources :plants
  resources :users
  # , only: [:show]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/plant.rb
class Plant < ApplicationRecord
    has_many :user_plants
    has_many :users, through: :user_plants
end

app/models/user.rb
class User < ApplicationRecord
    has_many :user_plants
    has_many :plants, through: :user_plants

    has_secure_password
end

app/models/user_plant.rb
class UserPlant < ApplicationRecord
    belongs_to :user
    belongs_to :plant

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController

    def index
        @plants = Plant.all
    end

    def show 
        @plant = Plant.find(params[:id])
        @user = User.find(session[:user_id])
    end

    def destroy 
        @plant = Plant.find(params[:id])
        @plant.destroy 
    
        redirect_to root_path
      end
    

    private

    def plant_params
        params.require(:plant).permit(:name, :height, :light, :water_frequency)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end

    # def create
        # @user = User.find_by(email: params[:email])
        # if @user == nil 
        #     flash[:errors] = ["User with this password not found"]
        #     redirect_to login_path
        # else 
    #         if @user && @user.authenticate(params[:password])
    #             session[:user_id] = @user.id
    #             # flash[:notices] = ["Logged in!"]
    #             redirect_to root_path
    #         else 
    #             flash[:errors] = ["User with this password not found"]
    #             redirect_to login_path
    #         end
        # end
    # end
    def create 
        
        @user = User.find_by(email: params[:email])
    
        if @user && @user.authenticate(params[:password])
          session[:user_id] = @user.id 
          redirect_to root_path
        else 
          flash[:error] = "Password or Email did not match"
          redirect_to login_path
        end 
      end 

    

    def destroy
        reset_session
        redirect_to login_path
    end
end

app/controllers/user_plants_controller.rb
class UserPlantsController < ApplicationController

    def new
        @user_plant = UserPlant.new
    
        @users = User.all
        @plants = Plant.all
      end 
    

    def index
        @user_plant = UserPlant.all
    end

    def show 
        @user_plant = UserPlant.find(params[:id])
    end

    def create
        user_plant = UserPlant.create(user_plant_params)
        redirect_to plant_path(user_plant.plant_id)
    end

    private

    def user_plant_params
        params.require(:user_plant).permit(:user_id, :plant_id, :review)
      end 
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end

    def index
      @users = User.all
    end


    def show
        @user = User.find(params[:id])
    end

    def create 
        user = User.create(user_params)
    
        if user.valid? 
          session[:user_id] = user.id
          redirect_to root_path

        else
          flash[:errors] = user.errors.full_messages
          redirect_to new_user_path 
        end 
      end 

    private

    def user_params
        params.require(:user).permit(:name, :email, :password)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

    # before_action :authentication_required, :current_user
    
    def homepage
        render 'homepage'
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/helpers/user_plants_helper.rb
module UserPlantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlntPckr</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/plants/index.html.erb
<h1>RANDOM PLANTS INDEX</h1>
<% @plants.each do |plant| %>
<p> <%= link_to plant.scientific_name, plant_path(plant)%> </p>
<% end %>

app/views/plants/show.html.erb
<h1>The Plant </h1>

  <% if flash[:success] %>
    <h2 style="color:green;"><%= flash[:success] %></h2>
  <% end %>

  <h3><%= @plant.scientific_name %></h3>
  <p> Height: <%= @plant.height %></p>
  <p> Light: <%= @plant.light %></p>
  <img src="<%=@plant.image_url%>" alt="<%= @plant.scientific_name %>">


  <%= button_to "Abandon Plant :( ", plant_path(@plant), method: :delete %>

 
  <%= button_to "Go to Profile Page", user_path(@user), method: :get %>

app/views/user_plants/index.html.erb
<h1>Here are all of the Plants you own</h1>

app/views/user_plants/new.html.erb
<h1>Lets get you a new plant!</h1>

<%= form_for @user_plant do |f| %>
  <%= f.label :user_id %>
  <%= f.collection_select :user_id, @users, :id, :name  %>

  <%= f.label :plant_id %>
  <%= f.collection_select :plant_id, @plants, :id, :scientific_name %>

  <%= f.submit %>

<% end %>

app/views/users/index.html.erb
<h1>User index </h1>

<% @users.each do |user| %>
<p> <%= link_to user.name, user_path(user)%> </p>
<% end %>

  <%= button_to "Return to Welcome Page", root_path, method: :get %>

app/views/users/new.html.erb
<h1>Create an Account</h1>

<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <p style="color:red;"><%= error %></p>
  <% end %>
<% end %>


<%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field  :name %>

  <%= f.label :email %>
  <%= f.text_field  :email %>

  <%= f.label :password %>
  <%= f.text_field :password %>

  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1>Hi, <%= @user.name %>! Here is your info:</h1>
  <h3><%= @user.name %></h3>
  <p> Email Address: <%= @user.email %></p>
  

<%# <% def plants%>
<%# <% UserPlants.all  do |up| %>
<%# <% if up.user_id == self %> 

<%# <%end%> 

<h2>These are your plants! </h2>  

<% @user.plants.each do |plant| %>
  <p><%= link_to plant.scientific_name, plant_path(plant) %></p>
<% end %>



  <%= button_to "Return to Welcome Page", root_path, method: :get %>
  <%= button_to "Return to Index", users_path(@user), method: :get %>

app/views/welcome/homepage.html.erb
<h1>Welcome!</h1>
<p>Would you like to add a plant to your care?</p>
<%# <p class="vertical-align"><%= link_to "Click here for a new plant!", new_user_plant_path %>
  <%= button_to "New Plant Please", new_user_plant_path, method: :get %>


<p>Would you like to see the plants you're caring for?</p>
<%# <p class="vertical-align"><%= link_to "Click here to see your plants!", index_user_path %></p>
  
  <%= button_to "Visit the Index", users_path(@user), method: :get %>

  <p>  <%= button_to "Return to Login", login_path, method: :get %> </p>